// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ControlApi.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AspNetMvc.Grpc {

  /// <summary>Holder for reflection information generated from ControlApi.proto</summary>
  public static partial class ControlApiReflection {

    #region Descriptor
    /// <summary>File descriptor for ControlApi.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ControlApiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDb250cm9sQXBpLnByb3RvEhBhc3BfbmV0X212Yy5HcnBjIj0KDlNldHRp",
            "bmdSZXF1ZXN0EisKBmVudGl0eRgBIAEoCzIbLmFzcF9uZXRfbXZjLkdycGMu",
            "Q21kRW50aXR5IiEKD1NldHRpbmdSZXNwb25zZRIOCgZyZXN1bHQYASABKAgi",
            "dAoJQ21kRW50aXR5EhEKCWRldmljZU1hYxgBIAEoCRIUCgxidXNpbmVzc0Nv",
            "ZGUYAiABKAUSFAoMZnVuY3Rpb25Db2RlGAMgASgFEhQKDGRhdGFUeXBlQ29k",
            "ZRgEIAEoBRISCgpwYXJhbXNKc29uGAUgASgJMmYKC0N0cmxTZXJ2aWNlElcK",
            "DlNlbmRTZXR0aW5nQ21kEiAuYXNwX25ldF9tdmMuR3JwYy5TZXR0aW5nUmVx",
            "dWVzdBohLmFzcF9uZXRfbXZjLkdycGMuU2V0dGluZ1Jlc3BvbnNlIgBiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AspNetMvc.Grpc.SettingRequest), global::AspNetMvc.Grpc.SettingRequest.Parser, new[]{ "Entity" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AspNetMvc.Grpc.SettingResponse), global::AspNetMvc.Grpc.SettingResponse.Parser, new[]{ "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AspNetMvc.Grpc.CmdEntity), global::AspNetMvc.Grpc.CmdEntity.Parser, new[]{ "DeviceMac", "BusinessCode", "FunctionCode", "DataTypeCode", "ParamsJson" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 获取设置命令的参数
  /// </summary>
  public sealed partial class SettingRequest : pb::IMessage<SettingRequest> {
    private static readonly pb::MessageParser<SettingRequest> _parser = new pb::MessageParser<SettingRequest>(() => new SettingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SettingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AspNetMvc.Grpc.ControlApiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingRequest(SettingRequest other) : this() {
      entity_ = other.entity_ != null ? other.entity_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingRequest Clone() {
      return new SettingRequest(this);
    }

    /// <summary>Field number for the "entity" field.</summary>
    public const int EntityFieldNumber = 1;
    private global::AspNetMvc.Grpc.CmdEntity entity_;
    /// <summary>
    /// 控制命令实体
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AspNetMvc.Grpc.CmdEntity Entity {
      get { return entity_; }
      set {
        entity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SettingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SettingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Entity, other.Entity)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (entity_ != null) hash ^= Entity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (entity_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Entity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (entity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Entity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SettingRequest other) {
      if (other == null) {
        return;
      }
      if (other.entity_ != null) {
        if (entity_ == null) {
          Entity = new global::AspNetMvc.Grpc.CmdEntity();
        }
        Entity.MergeFrom(other.Entity);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (entity_ == null) {
              Entity = new global::AspNetMvc.Grpc.CmdEntity();
            }
            input.ReadMessage(Entity);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 获取单个账号数据返回值
  /// </summary>
  public sealed partial class SettingResponse : pb::IMessage<SettingResponse> {
    private static readonly pb::MessageParser<SettingResponse> _parser = new pb::MessageParser<SettingResponse>(() => new SettingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SettingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AspNetMvc.Grpc.ControlApiReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingResponse(SettingResponse other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingResponse Clone() {
      return new SettingResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private bool result_;
    /// <summary>
    /// 控制结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SettingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SettingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != false) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != false) {
        output.WriteRawTag(8);
        output.WriteBool(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SettingResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != false) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 控制命令实体
  /// </summary>
  public sealed partial class CmdEntity : pb::IMessage<CmdEntity> {
    private static readonly pb::MessageParser<CmdEntity> _parser = new pb::MessageParser<CmdEntity>(() => new CmdEntity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CmdEntity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AspNetMvc.Grpc.ControlApiReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdEntity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdEntity(CmdEntity other) : this() {
      deviceMac_ = other.deviceMac_;
      businessCode_ = other.businessCode_;
      functionCode_ = other.functionCode_;
      dataTypeCode_ = other.dataTypeCode_;
      paramsJson_ = other.paramsJson_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CmdEntity Clone() {
      return new CmdEntity(this);
    }

    /// <summary>Field number for the "deviceMac" field.</summary>
    public const int DeviceMacFieldNumber = 1;
    private string deviceMac_ = "";
    /// <summary>
    /// 设备号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceMac {
      get { return deviceMac_; }
      set {
        deviceMac_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "businessCode" field.</summary>
    public const int BusinessCodeFieldNumber = 2;
    private int businessCode_;
    /// <summary>
    /// 业务类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BusinessCode {
      get { return businessCode_; }
      set {
        businessCode_ = value;
      }
    }

    /// <summary>Field number for the "functionCode" field.</summary>
    public const int FunctionCodeFieldNumber = 3;
    private int functionCode_;
    /// <summary>
    /// 功能类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FunctionCode {
      get { return functionCode_; }
      set {
        functionCode_ = value;
      }
    }

    /// <summary>Field number for the "dataTypeCode" field.</summary>
    public const int DataTypeCodeFieldNumber = 4;
    private int dataTypeCode_;
    /// <summary>
    /// 数据类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DataTypeCode {
      get { return dataTypeCode_; }
      set {
        dataTypeCode_ = value;
      }
    }

    /// <summary>Field number for the "paramsJson" field.</summary>
    public const int ParamsJsonFieldNumber = 5;
    private string paramsJson_ = "";
    /// <summary>
    /// 参数值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ParamsJson {
      get { return paramsJson_; }
      set {
        paramsJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CmdEntity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CmdEntity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DeviceMac != other.DeviceMac) return false;
      if (BusinessCode != other.BusinessCode) return false;
      if (FunctionCode != other.FunctionCode) return false;
      if (DataTypeCode != other.DataTypeCode) return false;
      if (ParamsJson != other.ParamsJson) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DeviceMac.Length != 0) hash ^= DeviceMac.GetHashCode();
      if (BusinessCode != 0) hash ^= BusinessCode.GetHashCode();
      if (FunctionCode != 0) hash ^= FunctionCode.GetHashCode();
      if (DataTypeCode != 0) hash ^= DataTypeCode.GetHashCode();
      if (ParamsJson.Length != 0) hash ^= ParamsJson.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DeviceMac.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DeviceMac);
      }
      if (BusinessCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BusinessCode);
      }
      if (FunctionCode != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FunctionCode);
      }
      if (DataTypeCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DataTypeCode);
      }
      if (ParamsJson.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ParamsJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DeviceMac.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceMac);
      }
      if (BusinessCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BusinessCode);
      }
      if (FunctionCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FunctionCode);
      }
      if (DataTypeCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DataTypeCode);
      }
      if (ParamsJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParamsJson);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CmdEntity other) {
      if (other == null) {
        return;
      }
      if (other.DeviceMac.Length != 0) {
        DeviceMac = other.DeviceMac;
      }
      if (other.BusinessCode != 0) {
        BusinessCode = other.BusinessCode;
      }
      if (other.FunctionCode != 0) {
        FunctionCode = other.FunctionCode;
      }
      if (other.DataTypeCode != 0) {
        DataTypeCode = other.DataTypeCode;
      }
      if (other.ParamsJson.Length != 0) {
        ParamsJson = other.ParamsJson;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DeviceMac = input.ReadString();
            break;
          }
          case 16: {
            BusinessCode = input.ReadInt32();
            break;
          }
          case 24: {
            FunctionCode = input.ReadInt32();
            break;
          }
          case 32: {
            DataTypeCode = input.ReadInt32();
            break;
          }
          case 42: {
            ParamsJson = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
