// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ControlApi.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AspNetMvc.Grpc {
  public static partial class CtrlService
  {
    static readonly string __ServiceName = "asp_net_mvc.Grpc.CtrlService";

    static readonly grpc::Marshaller<global::AspNetMvc.Grpc.SettingRequest> __Marshaller_asp_net_mvc_Grpc_SettingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AspNetMvc.Grpc.SettingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::AspNetMvc.Grpc.SettingResponse> __Marshaller_asp_net_mvc_Grpc_SettingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AspNetMvc.Grpc.SettingResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::AspNetMvc.Grpc.SettingRequest, global::AspNetMvc.Grpc.SettingResponse> __Method_SendSettingCmd = new grpc::Method<global::AspNetMvc.Grpc.SettingRequest, global::AspNetMvc.Grpc.SettingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendSettingCmd",
        __Marshaller_asp_net_mvc_Grpc_SettingRequest,
        __Marshaller_asp_net_mvc_Grpc_SettingResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AspNetMvc.Grpc.ControlApiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CtrlService</summary>
    [grpc::BindServiceMethod(typeof(CtrlService), "BindService")]
    public abstract partial class CtrlServiceBase
    {
      /// <summary>
      /// 获取设置命令的结果
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::AspNetMvc.Grpc.SettingResponse> SendSettingCmd(global::AspNetMvc.Grpc.SettingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CtrlService</summary>
    public partial class CtrlServiceClient : grpc::ClientBase<CtrlServiceClient>
    {
      /// <summary>Creates a new client for CtrlService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CtrlServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CtrlService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CtrlServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CtrlServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CtrlServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// 获取设置命令的结果
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AspNetMvc.Grpc.SettingResponse SendSettingCmd(global::AspNetMvc.Grpc.SettingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendSettingCmd(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 获取设置命令的结果
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AspNetMvc.Grpc.SettingResponse SendSettingCmd(global::AspNetMvc.Grpc.SettingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendSettingCmd, null, options, request);
      }
      /// <summary>
      /// 获取设置命令的结果
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AspNetMvc.Grpc.SettingResponse> SendSettingCmdAsync(global::AspNetMvc.Grpc.SettingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendSettingCmdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// 获取设置命令的结果
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AspNetMvc.Grpc.SettingResponse> SendSettingCmdAsync(global::AspNetMvc.Grpc.SettingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendSettingCmd, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CtrlServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CtrlServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CtrlServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendSettingCmd, serviceImpl.SendSettingCmd).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CtrlServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SendSettingCmd, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::AspNetMvc.Grpc.SettingRequest, global::AspNetMvc.Grpc.SettingResponse>(serviceImpl.SendSettingCmd));
    }

  }
}
#endregion
